# 2022-01-20 07:03:44.408864: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.2022-01-20 07:03:44.410913: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.Traceback (most recent call last):  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/gen_boosted_trees_ops.py", line 1137, in boosted_trees_make_quantile_summaries    _result = pywrap_tfe.TFE_Py_FastPathExecute(tensorflow.python.eager.core._NotOkStatusException: InvalidArgumentError: Weights should be a single value or same size as features. [Op:BoostedTreesMakeQuantileSummaries]During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/home/neo/mlfuzz/tensorflow/synthesized/all-crashes/all/BoostedTreesMakeQuantileSummaries_567e2465786ae5933ed9d0ab5c0fe532.py", line 7, in <module>    tf.raw_ops.BoostedTreesMakeQuantileSummaries(float_values=arg_0, example_weights=arg_1, epsilon=arg_2, name=arg_3)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper    return f(**kwargs)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/gen_boosted_trees_ops.py", line 1142, in boosted_trees_make_quantile_summaries    _ops.raise_from_not_ok_status(e, name)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 6939, in raise_from_not_ok_status    message = e.message + (" name: " + name if name is not None else "")  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py", line 1399, in r_binary_op_wrapper    y, x = maybe_promote_tensors(y, x)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py", line 1335, in maybe_promote_tensors    ops.convert_to_tensor(tensor, dtype, name="x"))  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped    return func(*args, **kwargs)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 346, in _constant_tensor_conversion_function    return constant(v, dtype=dtype, name=name)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 271, in constant    return _constant_impl(value, dtype, shape, name, verify_shape=False,  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 308, in _constant_eager_impl    t = convert_to_eager_tensor(value, ctx, dtype)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor    return ops.EagerTensor(value, ctx.device_name, dtype)TypeError: Cannot convert ' name: ' to EagerTensor of dtype float

import tensorflow as tf

arg_0 = tf.constant(-3.5e+35, shape=[6], dtype=tf.float32)
arg_1 = tf.constant(1.2, shape=[6], dtype=tf.float32)
arg_2 = tf.constant(1.2, shape=[6], dtype=tf.float32)
arg_3 = tf.constant(1.2, shape=[6], dtype=tf.float32)
tf.raw_ops.BoostedTreesMakeQuantileSummaries(float_values=arg_0, example_weights=arg_1, epsilon=arg_2, name=arg_3)